# general parameters
seed:  3407
save_load_path: experiments/baseline-script-check 
train: True
inference: True
make_plots: True
save_model_optimizer: False
load_model_optimizer: False

# data parameters
data_path: /content/drive/MyDrive/Emulator_Phase_2/Simulator_v1.7/results/v1.7_R0_Experiments/
train_fraction: 0.8
val_fraction: 0.1
test_fraction: 0.1
block_count: 1000
t_steps: 100
context_len: 5
x_dim: 10
y_dim: 10
num_feat_cols: 3
num_stat_cols: 2
stats: ["cumulative_positive_tested", "current_hospitalized", "current_asymptomatic_free"]

# training parameters
train_batch_size: 4
val_batch_size: 4
train_epochs: 2
learning_rate: 0.001
# model = feedforward, dilatedcnn,
model: feedforward
# loss = mse
loss_fn: mse
# optimizer = adam, sgd 
optimizer: adam
# scheduler = multiplicative, step, decay
scheduler: step

# wandb parameters
use_wandb: True
wandb_path: baseline-script-check
wandb_project: neural-agent-based-modeling 